server:
  port: 123
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        domain: baidu.cn
        http-only: true
        path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhibei?useUnicode\=true&characterEncoding\=utf-8&useSSL\=false
    username: *
    password: *
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: true
    encoding: UTF-8
    servlet:
      content-type: text/html
  mail:
    port: 123
    host: smtp.sbx0.com
    username: *
    password: *
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    freemarker:
      allow-request-override: false
      cache: true
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
logging:
  config: classpath:logback-spring.xml
pay:
  alipay:
    gatewayUrl: *
    appId: *
    merchantPrivateKey: *
    alipayPublicKey: *
    returnUrl: *
    notifyUrl: *
    signType: RSA2
    format: json
    charset: UTF-8
    maxQueryRetry: 5
    queryDuration: 5000
    maxCancelRetry: 3
    cancelDuration: 3000
config:
  KEY: *
  DOMAIN: *
  UploadFileFolder: *
  StaticAccessPath: *
  FORM_WHERE: *