server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        domain: 192.168.0.185
        http-only: true
        path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhibei?useUnicode\=true&characterEncoding\=utf-8&useSSL\=false
    username: root
    password: *
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    port: *
    host: *
    username: *
    password: *
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    freemarker:
      allow-request-override: false
      cache: true
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
config:
  KEY: *
  #  DOMAIN: sbx0.cn
  DOMAIN: 192.168.0.185
  UploadFileFolder: D://upload/
  #  UploadFileFolder: /root/upload/
  StaticAccessPath: /upload/**
  FORM_WHERE: *
pay:
  alipay:
    gatewayUrl: *
    appId: *
    merchantPrivateKey: *
    alipayPublicKey: *
    returnUrl: *
    notifyUrl: *
    signType: RSA2
    format: json
    charset: UTF-8
    maxQueryRetry: 5
    queryDuration: 5000
    maxCancelRetry: 3
    cancelDuration: 3000