server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        domain: sbx0.cn
        http-only: true
        path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhibei?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: test
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
  mail:
    port: 4312
    host: smtp.qq.com
    username: sdfjsdifij
    password: dfadsijfoisdjf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    freemarker:
      allow-request-override: false
      cache: true
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
logging:
  config: classpath:logback-spring.xml
pay:
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/way.do
    appId: 20162343243243242343240212
    merchantPrivateKey: MIIEvwIBADANsdafasdfasdfBgkqhkiG9w0BAQEFAASCBKksdfwggSlAgEAAoIBAQCbdyB6PUB0K71hHxoEUw4z3UeLEm9Zm8aZOeDPCE536T6WICpiyt4Nu8m0GkuyxyQja5ZGIQNXbAkeM+CJteV9p0b4L2XjiUa2GXzPRjaHVtqPfHbZo6y2rsi9sbEIJwGqmJtfHYqyT8aEeAXBST+8dMpZlTcQGdVde5TtplQ6g0bHZeykPk90l8zaep2DBKMthQlJTdm79PyVovuoJlppLDaslZBd5BKMB4nfLLALjbJMWsn1MgTfN+ORZMZain//KQVtIpR0QPIoLrcGbWkFxULh2bZza6d+utTwpke4zj48tN865/l9lUif9rnqLyEzeg34pnTiGrKFYPQAWkYLAgMBAAECggEAGf/CHq8/qC3obeWVpEN/jIzk+g0LMiErBVT4k6b/+G25WcHnVL44hHNzN/ttzWggUwwbBX9f367hl3t1gZI53tmqtLa4g2ThvnJkvQUw+VE9G+HkvmDw8Vwplg+xW3uqe60pzq5SE5/jwyOPUtO9JPcjH/gkTT0Ewa15KoU2cNJgTIXqfF5POzX/zEP7m8Op6IPhVn3VTvxybPvL68JfpqvilOv5luKepnV1YrRzKMBwU/jXEAI7aNwedukETPo3BZ5avK8oubsIdIqzo7bz5Ou4X4CZmEAwHqxXvDONZMEKrV6DDbZ+9J4P3TDRNBqz2+hcInGM8Yn1tcS0nSGEAQKBgQDfYvJ8axZLFWRn6r2c7qfV63Z2CMkTF67wIAxoBrpdc5OfY3uxzoEtiotJ5OBviw7eHWHeEiXSSm/DSTfocQ5ffkpRJ7i7TrKSqEIwA0+d/nJtVJWePQuuYqkRY3dTGr0scieeG9D7vngtuXkMTnBEinGr90fN8CSqd2DU5IWOqwKBgQCyKaGdw5oa8lNG/FtG2GWjfYfODtU5cua3Z22iB3zpsDAbMNfBV8pJUzwRElwvYEVv7DxOt3qNgqrN/gDhIrL4hNr1ai5MywcIzlT6h4peXyhLAyca/tXfuR2SxJq8vR9Iw/vdzKXUwE31Q+faVxOCz/z7ugrz3B+4FZr5UeCmIQKBgQCIXpc5bQZG/+AzsBHg47CB3ySKGgLmLOcWn/ny52iN9CiCfPDeMvqZGqK9kYORlIqW/cjpEJsWLWrdBK2ksJ/dm/MyZ9VWQ0ywSxdcyCiqgtLH+4L6/rlK09/yRY5qpUAnCek1lDWX+UbUYw2Kfbf7n6iVGngzOA6qIgZy8K630QKBgQCtfrUPuQc87nYCToVkfB6eEwRIuVES3L2oJGQywS/3Mcfm8q1obmFi/lckGMkEqa90yov/69TAMVq7tnqMwwmd0WKYUoo75go3nRZL0eoA9JF8WtmeBEOp1c7iueolmdX5OkDvQPbMM2i3SyVhDiLF5FzrlcRMrTOGRCPiXsVxgQKBgQDUdQ9g1E9yN8lHr1qn11krR5T4bLSepRg8JIJHZqYcvyPGEIfkvkxv3VXS2YmmIt3+fpq335ETNR4N51AR5IvzIrQPTjr9EGBl8rfNGqUF44DeWZ+YjCWYQayjiNRvih+LDNHddf9XLQVKw37k/rnmI4gOhEN/DkarhjNE2dPuKw==
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AsadfasdfafMIIBCgKCAQEA02NDOaEsC3AlW+2FIui+4OlvKTKyCcNNVrJbVpfhRhpXf/Ksex6zoH3UlXWKWOsHjm1rNK13nJGXXGgzjXaiDJSgu2TKcTIOoLodoSmqAHrbYeXk0wUmlAEA021lFZvKdaUQllmsaktS3pR4/pCgPlVtfKbfiAa/QosBvPBYnIzUi3GF1o8knal3u71YrzG+GYJNe8LEyFfg6ZuCdB1C2FQYHZkJv+PwmILBHkwllthOUMr/8naUpLQ7RcwUniO9CT7g51t8bPgXVBJH3KkKG0Rl2UTH9rgKEqHF3P1GOwRTPaR1MS0lE+8O1j2XbHNCJex6pI1u+KYDbXcx6XnjUQIDAQAB
    returnUrl: https://test.cn/set/return
    notifyUrl: https://test.cn/setest/notify
    signType: RSA2
    format: json
    charset: UTF-8
    maxQueryRetry: 5
    queryDuration: 5000
    maxCancelRetry: 3
    cancelDuration: 3000
mybatis:
  config-location: classpath:mybatis-config.xml
config:
  KEY: adsgdfaserwr
  DOMAIN: test.cn
  UploadFileFolder: /c/sffs/
  StaticAccessPath: /upload/**
  FORM_WHERE: tset@est.cn