### 登录
POST {{serverConfig}}/user/base/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

email={{email}}&password={{password}}

### 获取自己的钱包
GET {{serverConfig}}/wallet/base/my
Accept: application/json

###
